### ISSUE TITLE
[Feature Request] Ability to work on page translated by Google Translate

### ISSUE THREAD

**Issue by Krazsn** [pelmers/moz-text-rewriter#10]
Page translated by Google Translate is inside an Iframe and Rewrite doesn't work on text inside the iframe currently.

**Comment by pelmers** [comment]
Turns out this is possible to fix with a one line change to the manifest: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts.

I can expect to push an update in the next few days.
<img width="683" alt="Screenshot 2020-11-18 215535" src="https://user-images.githubusercontent.com/2406051/99627296-dbb29f00-29e8-11eb-923a-183ccb09cb9b.png">

**Comment by pelmers** [comment]
fixed in eb74802957123f7ff99eca9a37abda6e3341c8c8 (awaiting review)
